# Настройка парсинга категорий
categories:
    # Настройка работы с страницами категорий
    # Если end и max не указаны (равны null или ~) или меньше start, то парсится страница с номером start
    # Если end не null или ~, то max игнорируется.
    page:
        # Указание с какой страницы начинать парсинг
        start: 1

        # Указание до какой страниц (включительно) парсить. Если указано end, то max игнорируется.
        end: ~

        # Количество страниц, которые будут распарсены
        max: ~

    # Список "корней" категорий объявлений: Работа, Услуги, Техника и т.п.
    urls:
        - https://www.avito.ru/magnitogorsk/vakansii


# Список адресов объявлений
ad_urls: ~
#ad_urls:
#    - https://www.avito.ru/magnitogorsk/tovary_dlya_zhivotnyh/kletka_voler_596183787
#    - https://www.avito.ru/magnitogorsk/tovary_dlya_zhivotnyh/gigienicheskie_trusiki_204464036
#    - https://www.avito.ru/magnitogorsk/sobaki/amerikanskaya_akita_597193616
#    - https://www.avito.ru/magnitogorsk/predlozheniya_uslug/scheben_skala_otsev_581011516
#    - https://www.avito.ru/magnitogorsk/vakansii/pomoschnik_avtomehanika_344371908

# Сколько нужно набрать телефонов. Если null или ~ -- парсинг, пока не закончатся страницы ad_urls и найденные
# адреса объявлений у категорий (categories/urls)
need_phones: 10

# Файл, в который будут сохранены результаты парсинга (null или ~ -- не нужно сохранять в файл)
# mode допускает следующие варианты:
#   w -- перезаписывание файла
#   a -- добавление в конец файла
out:
    file_name: out.txt
    mode: w

# Информация о используемой прокси
proxy:
    url: ~
    type: http
    enabled: false

# Настройка логирования
log:
    # Файл, в котором логируются события скрипта (~ -- если не нужно логировать в файл)
    out: log.txt

    # Формат логированных сообщений
    format: ~

    enabled: true