# Настройка парсинга категорий
categories:
    # Настройка работы с страницами категорий
    # Если end и max не указаны (равны null или ~) или меньше start, то парсится страница с номером start
    # Если end не null или ~, то max игнорируется.
    page:
        # Указание с какой страницы начинать парсинг
        start: 1

        # Указание до какой страниц (включительно) парсить. Если указано end, то max игнорируется.
        end: ~

        # Количество страниц, которые будут распарсены
        max: ~

    # Список "корней" категорий объявлений: Работа, Услуги, Техника и т.п.
    urls:
        - http://kiev.ko.olx.ua/elektronika/telefony/
        - http://kiev.ko.olx.ua/zhivotnye/
        - http://olx.ua/rabota/ohrana-bezopasnost/


# Список адресов объявлений
ad_urls:
    - http://kiev.ko.olx.ua/obyavlenie/sony-xperia-z3-dual-black-IDeSjxG.html#b9de1eb356
    - http://kiev.ko.olx.ua/obyavlenie/prodam-samsung-galaxy-s2-s-kuchey-priyatnostey-IDeYoQC.html#b9de1eb356
    - http://zaporozhe.zap.olx.ua/obyavlenie/perevodchik-korrespondentsii-i-ustnogo-perevoda-IDejM4E.html#a47512b209;promoted
    - http://krivoyrog.dnp.olx.ua/obyavlenie/lg-p705-optimus-l7-IDeWHN0.html#66d81f54b6

# Сколько нужно набрать телефонов. Если null или ~ -- парсинг, пока не закончатся страницы ad_urls и найденные
# адреса объявлений у категорий (categories/urls)
need_phones: 20

# Файл, в который будут сохранены результаты парсинга (null или ~ -- не нужно сохранять в файл)
# mode допускает следующие варианты:
#   w -- перезаписывание файла
#   a -- добавление в конец файла
out:
    file_name: out.txt
    mode: w

# Информация о используемой прокси
proxy:
    url: ~
    type: http
    enabled: false

# Настройка логирования
log:
    # Файл, в котором логируются события скрипта (~ -- если не нужно логировать в файл)
    out: log.txt

    # Формат логированных сообщений
    format: ~

    enabled: true